name: Python application

on:
  push:
    branches:
      - feature/APIv2

env:
  AZURE_WEBAPP_NAME: apiterrabyte # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./backend" # Set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install setuptools==63.2.0 wheel
          pip install -r requirements.txt

      - name: Deploy web app using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Logout
        run: |
          az logout
