name: Backend Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  automated-backend-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
            pip install -r backend/requirements.txt
            pip install pytest pytest-cov codecov coverage

      - name: Run tests with pytest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          pytest --cov=backend backend/test/
          pytest --cov-report xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
