name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

jobs:
  format-lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Run Formatter
        run: pnpm run format
        working-directory: ./frontend

      - name: Run Linter
        run: pnpm run lint
        working-directory: ./frontend

      - name: Run Build
        run: pnpm run build
        working-directory: ./frontend
